import type { Language } from "../../types/language";

export const LANGUAGES: Language[] = [
  // English
  { code: "en-GB", name: "English (UK)" },
  { code: "en-US", name: "English (US)" },

  // Europe
  { code: "es-ES", name: "Spanish" },
  { code: "fr-FR", name: "French" },
  { code: "de-DE", name: "German" },
  { code: "it-IT", name: "Italian" },
  { code: "pt-PT", name: "Portuguese" },
  { code: "nl-NL", name: "Dutch" },
  { code: "el-GR", name: "Greek" },
  { code: "ro-RO", name: "Romanian" },
  { code: "cs-CZ", name: "Czech" },
  { code: "sk-SK", name: "Slovak" },
  { code: "pl-PL", name: "Polish" },
  { code: "hu-HU", name: "Hungarian" },
  { code: "bg-BG", name: "Bulgarian" },
  { code: "hr-HR", name: "Croatian" },
  { code: "sr-RS", name: "Serbian" },
  { code: "sl-SI", name: "Slovenian" },
  { code: "uk-UA", name: "Ukrainian" },
  { code: "ru-RU", name: "Russian" },
  { code: "sv-SE", name: "Swedish" },
  { code: "da-DK", name: "Danish" },
  { code: "no-NO", name: "Norwegian" },
  { code: "fi-FI", name: "Finnish" },
  { code: "is-IS", name: "Icelandic" },
  { code: "ga-IE", name: "Irish" },
  { code: "cy-GB", name: "Welsh" },

  // Middle East
  { code: "ar-SA", name: "Arabic" },
  { code: "he-IL", name: "Hebrew" },
  { code: "fa-IR", name: "Persian" },
  { code: "tr-TR", name: "Turkish" },
  { code: "ur-PK", name: "Urdu" },

  // Asia
  { code: "zh-CN", name: "Chinese (Simplified)" },
  { code: "zh-TW", name: "Chinese (Traditional)" },
  { code: "ja-JP", name: "Japanese" },
  { code: "ko-KR", name: "Korean" },
  { code: "hi-IN", name: "Hindi" },
  { code: "bn-IN", name: "Bengali" },
  { code: "pa-IN", name: "Punjabi" },
  { code: "gu-IN", name: "Gujarati" },
  { code: "mr-IN", name: "Marathi" },
  { code: "ta-IN", name: "Tamil" },
  { code: "te-IN", name: "Telugu" },
  { code: "kn-IN", name: "Kannada" },
  { code: "ne-NP", name: "Nepali" },
  { code: "si-LK", name: "Sinhala" },
  { code: "th-TH", name: "Thai" },
  { code: "vi-VN", name: "Vietnamese" },
  { code: "id-ID", name: "Indonesian" },
  { code: "ms-MY", name: "Malay" },
  { code: "tl-PH", name: "Filipino" },

  // Africa
  { code: "af-ZA", name: "Afrikaans" },
  { code: "am-ET", name: "Amharic" },
  { code: "ha-NE", name: "Hausa" },
  { code: "sw-KE", name: "Swahili" },
  { code: "so-SO", name: "Somali" },
  { code: "zu-ZA", name: "Zulu" },
  { code: "xh-ZA", name: "Xhosa" },
  { code: "st-ZA", name: "Southern Sotho" },
  { code: "tn-ZA", name: "Tswana" },
  { code: "ny-MW", name: "Chichewa" },
  { code: "rw-RW", name: "Kinyarwanda" },
  { code: "sn-ZW", name: "Shona" },
];